Workflow test for assembly

diff --git a/.github/workflows/assembly-script.yml b/.github/workflows/assembly-script.yml
--- a/.github/workflows/assembly-script.yml
+++ b/.github/workflows/assembly-script.yml
@@ -25,9 +25,17 @@ jobs:
         # stop the build if there are Python syntax errors or undefined names
         flake8 assembler/assmbler.py assembler/main.py --count --select=E9,F63,F7,F82 --show-source --statistics
 
-    - name: Run assembly script and check Python runtime errors for each file in testcases
-      run: |
-        set -e
-        for file in testcases/*; do
-          ./run_assembler.sh "$file" "output/$(basename "$file" .asm).out"
-        done
+        - name: Run assembly script and check Python runtime errors for each file in testcases
+        run: |
+          set +e
+          all_errors=0
+          for file in testcases/*; do
+            ./run_assembler.sh "$file" "output/$(basename "$file" .asm).out"
+            if [ $? -ne 0 ]; then
+              echo "Error occurred while processing $file"
+              all_errors=1
+            fi
+          done
+          if [ $all_errors -ne 0 ]; then
+            exit 1
+          fi
